android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true

## Limit the footprint of the Gradle daemon while building on TC
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.daemon=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
#android.r8.optimizedResourceShrinking=false
android.disallowKotlinSourceSets=true